### Trabalho Prático - ANADI
#### Grupo: 
Mariana Martins
Luna Gomes
Samara Miranda



#### 3. Tratamento de Dados (Valores NA e Outliers)

### 1. Importação de Bibliotecas e Dados

In [4]:
!pip install pandas numpy matplotlib seaborn scipy statsmodels plotly streamlit openpyxl

Requirement already satisfied: pandas in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (1.26.4)
Requirement already satisfied: matplotlib in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (0.13.2)
Requirement already satisfied: scipy in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (1.15.3)
Requirement already satisfied: statsmodels in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (0.14.6)
Requirement already satisfied: plotly in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (6.6.0)
Requirement already satisfied: streamlit in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (1.55.0)
Requirement already satisfied: openpyxl in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: patsy>=0.5.6 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from plotly) (2.17.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (7.0.3)
Requirement already satisfied: click<9,>=7.0 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (3.1.46)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (4.25.8)
Requirement already satisfied: pyarrow>=7.0 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (6.5.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: colorama in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.10.5)
Requirement already satisfied: et-xmlfile in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in c:\users\maria\anaconda3\envs\tf217\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### 2. Análise Exploratória (Estatística Descritiva)

In [4]:
import pandas as pd
import numpy as np

# 1. Carregar os dados (ajustado para os nomes dos ficheiros que enviaste)
# O parâmetro na_values converte automaticamente "N/D" em valores nulos (NaN)
ip_data = pd.read_excel('IP_data.xlsx', na_values='N/D')
ptd_data = pd.read_excel('PTD_data.xlsx', na_values='N/D')

# 2. Inspeção Rápida: Ver as primeiras linhas e os tipos de dados
print("--- INFO IP DATA ---")
print(ip_data.info())
print("\n--- INFO PTD DATA ---")
print(ptd_data.info())

# Visualizar as primeiras 5 linhas de cada um para confirmar a leitura
display(ip_data.head())
display(ptd_data.head())

--- INFO IP DATA ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9300 entries, 0 to 9299
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ano                           9300 non-null   int64
 1   Mês                           9300 non-null   int64
 2   Distrito                      9300 non-null   object
 3   Concelho                      9300 non-null   object
 4   Freguesia                     9300 non-null   object
 5   Tipo de Lâmpada               9300 non-null   object
 6   Luminárias                    9299 non-null   float64
 7   Lâmpadas por Luminária        9258 non-null   float64
 8   Lâmpadas                      9258 non-null   float64
 9   Potência Instalada Total (W)  8483 non-null   float64
 10  CodDistrito                   9300 non-null   int64
 11  CodDistritoConcelho           9300 non-null   int64
 12  coddistritoconcelhofreguesia  9300 non-null   object
dtypes: float64(4), int64(4), object(5)
memory usage: 944.7+ KB
None

--- INFO PTD DATA ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72027 entries, 0 to 72026
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Código de Instalação           72027 non-null  object
 1   Coordenadas Geográficas        72027 non-null  object
 2   Potência instalada [kVA]       72027 non-null  int64
 3   Nível de Utilização [%]        68963 non-null  object
 4   Tipo Construtivo               72027 non-null  object
 5   Potência Contratada [kVA]      50847 non-null  float64
 6   Número de Clientes             72027 non-null  object
 7   Potência Geração [kW]          1836 non-null   float64
 8   Número de Clientes Produtores  72027 non-null  object
 9   CodDistritoConcelho            72027 non-null  int64
 10  Concelho                       72027 non-null  object
dtypes: float64(2), int64(2), object(7)
memory usage: 6.0+ MB
None

,Ano,Mês,Distrito,Concelho,Freguesia,Tipo de Lâmpada,Luminárias,Lâmpadas por Luminária,Lâmpadas,Potência Instalada Total (W),CodDistrito,CodDistritoConcelho,coddistritoconcelhofreguesia
0,2026,2,Leiria,Alvaiázere,Almoster,LED,716.0,715.0,715.0,29010.800171,10,1002,100201
1,2026,2,Leiria,Alvaiázere,Almoster,Outros/Não definido,23.0,23.0,23.0,225.000000,10,1002,100201
2,2026,2,Leiria,Alvaiázere,Almoster,Sódio,27.0,26.0,26.0,1890.000000,10,1002,100201
3,2026,2,Leiria,Alvaiázere,Pelmá,Mercúrio,1.0,1.0,1.0,50.000000,10,1002,100205
4,2026,2,Leiria,Alvaiázere,Alvaiázere,Mercúrio,3.0,3.0,3.0,150.000000,10,1002,100208

,Código de Instalação,Coordenadas Geográficas,Potência instalada [kVA],Nível de Utilização [%],Tipo Construtivo,Potência Contratada [kVA],Número de Clientes,Potência Geração [kW],Número de Clientes Produtores,CodDistritoConcelho,Concelho
0,1307D2012500,"41.1849010463209, -8.14785254356171",400,60%-79%,Cabine pré-fabricada,1052.69,131,NaN,<20,1307,Marco de Canaveses
1,1307D2012900,"41.0869934226954, -8.24673374651495",250,60%-79%,Cabine baixa integrada em edifício,775.20,115,NaN,<20,1307,Marco de Canaveses
2,1307D2013100,"41.1129221154249, -8.21276525945275",250,60%-79%,Cabine alta,1104.19,176,NaN,<20,1307,Marco de Canaveses
3,1307D2013800,"41.1329530486552, -8.13563404382479",50,+100%,Aéreo - AS,238.07,36,NaN,<20,1307,Marco de Canaveses
4,1307D2015100,"41.1228444565974, -8.11290068900831",250,0%-19%,Aéreo - AI,608.51,94,NaN,<20,1307,Marco de Canaveses